### ISSUE TITLE
issue with get_all_web_service_custom_policies()

### ISSUE THREAD

**Issue by RandallLasini** [imperva/imperva-sdk-python#58]
I can connect with MxConnection and get a version number back (its how I verify its working)
but when I attempt to iterate over the custom web server policies it crashes:

MX version 14.6.0.30

Traceback (most recent call last):
  File "policiesSync.py", line 17, in <module>
    for pol_c in mx_cloud.get_all_web_service_custom_policies():
  File "/home/XXXX/.local/lib/python3.8/site-packages/imperva_sdk/MxConnection.py", line 889, in get_all_web_service_custom_policies
    return WebServiceCustomPolicy._get_all_web_service_custom_policies(connection=self)
  File "/home/XXXX/.local/lib/python3.8/site-packages/imperva_sdk/WebServiceCustomPolicy.py", line 240, in _get_all_web_service_custom_policies
    pol_obj = connection.get_web_service_custom_policy(Name=name)
  File "/home/XXXX/.local/lib/python3.8/site-packages/imperva_sdk/MxConnection.py", line 899, in get_web_service_custom_policy
    return WebServiceCustomPolicy._get_web_service_custom_policy(connection=self, Name=Name)
  File "/home/XXXX/.local/lib/python3.8/site-packages/imperva_sdk/WebServiceCustomPolicy.py", line 246, in _get_web_service_custom_policy
    validate_string(Name=Name)
  File "/home/XXXX/.local/lib/python3.8/site-packages/imperva_sdk/core.py", line 54, in validate_string
    raise MxException("Invalid string value for parameter - '%s - %s'" % (param, kwargs[param]))
imperva_sdk.core.MxException: Invalid string value for parameter - 'Name - WPS Hide Login Plugin Bypass #1'

I checked by the web gui and WPS Hide Login Plugin Bypass #1 is an actual policy name, so I can see its doing something.

**Comment by RandallLasini** [comment]
okay - digging into the code I found a comment in WebServiceCustomPolicy.py
**# Bug - we have policies with '/' character that don't work with the API...**

So I added a similar bypass for the # (and after that worked for the ! character)

**>       if '#' in name:
>         continue
>       if '!' in name:
>         continue**

Its a work around, but I dont have time to fix.   nor to commit it to the source.
